<a href="https://colab.research.google.com/github/xtric6/Hamoye-StageBQUIZ/blob/main/Copy_of_Stability_of_grid_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Stability of the Grid System.csv to Stability of the Grid System (1).csv


In [ ]:
import io
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
df = pd.read_csv(io.BytesIO(uploaded['Stability of the Grid System.csv']))

##Predictive features:

**'tau1' to 'tau4'**: the reaction time of each network participant, a real value within the range 0.5 to 10 ('tau1' corresponds to the supplier node, 'tau2' to 'tau4' to the consumer nodes);

**'p1' to 'p4'**:  nominal power produced (positive) or consumed (negative) by each network participant, a real value within the range -2.0 to -0.5 for consumers ('p2' to 'p4'). As the total power consumed equals the total power generated, p1 (supplier node) = - (p2 + p3 + p4);

**'g1' to 'g4'**: price elasticity coefficient for each network participant, a real value within the range 0.05 to 1.00 ('g1' corresponds to the supplier node, 'g2' to 'g4' to the consumer nodes; 'g' stands for 'gamma');

##Dependent variables:

**'stab'**: the maximum real part of the characteristic differential equation root (if positive, the system is linearly unstable; if negative, linearly stable);

**'stabf'**: a categorical (binary) label ('stable' or 'unstable').

In [ ]:
df.head()

tau1      tau2      tau3  ...        g4      stab     stabf
0  2.959060  3.079885  8.381025  ...  0.958034  0.055347  unstable
1  9.304097  4.902524  3.047541  ...  0.781760 -0.005957    stable
2  8.971707  8.848428  3.046479  ...  0.109853  0.003471  unstable
3  0.716415  7.669600  4.486641  ...  0.362718  0.028871  unstable
4  3.134112  7.608772  4.943759  ...  0.820923  0.049860  unstable

[5 rows x 14 columns]

In [ ]:
df['stabf'].value_counts()

unstable    6380
stable      3620
Name: stabf, dtype: int64

Our output values is not balanced

In [ ]:
df_stable= df[df.stabf== 'stable' ]
df_unstable = df[df.stabf== 'unstable' ].sample( 3700 )
df_data = df_stable.append(df_unstable) 

In [ ]:
df_data['stabf'].value_counts()

unstable    3700
stable      3620
Name: stabf, dtype: int64

In [ ]:
import sklearn.utils
df_data = sklearn.utils.shuffle(df_data)
df_data= df_data.reset_index(drop= True )
df_data.stabf.value_counts()

unstable    3700
stable      3620
Name: stabf, dtype: int64

In [ ]:
df_data.drop('stab',axis ='columns',inplace = True)

In [ ]:
df_data.head()

tau1      tau2      tau3  ...        g3        g4     stabf
0  4.114349  0.535156  5.945791  ...  0.511837  0.510802    stable
1  6.990906  7.768754  0.980863  ...  0.207100  0.750979  unstable
2  1.522943  2.751999  5.880115  ...  0.607319  0.419435    stable
3  4.139122  0.625133  6.254096  ...  0.441094  0.634096  unstable
4  1.818383  7.907368  4.400380  ...  0.257000  0.492245    stable

[5 rows x 13 columns]

In [ ]:
df_data.isnull().sum()

tau1     0
tau2     0
tau3     0
tau4     0
p1       0
p2       0
p3       0
p4       0
g1       0
g2       0
g3       0
g4       0
stabf    0
dtype: int64

There are no missing values

In [ ]:
df_data.duplicated().sum()

0

There are no duplicated rows

In [ ]:
df_data.describe()

tau1         tau2  ...           g3           g4
count  7320.000000  7320.000000  ...  7320.000000  7320.000000
mean      5.086509     5.064885  ...     0.507351     0.510662
std       2.790081     2.791803  ...     0.272991     0.274618
min       0.500793     0.500141  ...     0.050054     0.050028
25%       2.596881     2.588398  ...     0.269616     0.270973
50%       5.019306     4.962807  ...     0.500680     0.502469
75%       7.518608     7.486860  ...     0.741385     0.748157
max       9.999469     9.999837  ...     0.999839     0.999930

[8 rows x 12 columns]

In [ ]:
X = df_data.iloc[:, :-1]
y = df_data.iloc[:, -1]

In [ ]:
print(X)

          tau1      tau2      tau3  ...        g2        g3        g4
0     4.114349  0.535156  5.945791  ...  0.670605  0.511837  0.510802
1     6.990906  7.768754  0.980863  ...  0.860724  0.207100  0.750979
2     1.522943  2.751999  5.880115  ...  0.846519  0.607319  0.419435
3     4.139122  0.625133  6.254096  ...  0.168549  0.441094  0.634096
4     1.818383  7.907368  4.400380  ...  0.112007  0.257000  0.492245
...        ...       ...       ...  ...       ...       ...       ...
7315  5.762545  4.715287  7.722105  ...  0.627977  0.763911  0.151395
7316  1.114636  0.709629  4.732685  ...  0.929018  0.513093  0.686613
7317  2.904002  8.041284  1.353475  ...  0.379086  0.340420  0.531401
7318  0.985954  9.327821  9.605089  ...  0.415517  0.904829  0.474935
7319  4.055062  0.593715  9.240600  ...  0.469617  0.621539  0.104891

[7320 rows x 12 columns]


In [ ]:
print(y)

0         stable
1       unstable
2         stable
3       unstable
4         stable
          ...   
7315    unstable
7316      stable
7317      stable
7318      stable
7319      stable
Name: stabf, Length: 7320, dtype: object


##Encoding the dependent variable

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[0 1 0 ... 0 0 0]


Label reprrsentation after labelEncoder

0 : stable

1 : unstable

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 1)

In [ ]:
pd.value_counts(y_train)

1    2944
0    2912
dtype: int64

training labels are balanced no need to apply SMOTE

In [ ]:
print(X_train)

          tau1      tau2      tau3  ...        g2        g3        g4
1554  5.147901  5.792541  1.123032  ...  0.602622  0.231028  0.716735
3665  1.467618  9.389085  6.019740  ...  0.273217  0.526145  0.851163
2907  8.183637  1.088214  3.942842  ...  0.365977  0.352944  0.552201
440   9.191444  8.727296  2.021477  ...  0.636110  0.484847  0.241855
6214  3.156690  9.878725  5.247346  ...  0.497677  0.927046  0.901810
...        ...       ...       ...  ...       ...       ...       ...
905   0.736947  2.059460  1.682176  ...  0.212757  0.479230  0.627937
5192  5.827787  7.710060  2.088683  ...  0.480958  0.228402  0.922898
3980  1.341493  6.172060  4.406919  ...  0.869085  0.144689  0.852452
235   8.528889  9.588129  2.395148  ...  0.785985  0.877627  0.102104
5157  2.961069  4.488062  7.290979  ...  0.775241  0.889565  0.998961

[5856 rows x 12 columns]


In [ ]:
print(X_test)

          tau1      tau2      tau3  ...        g2        g3        g4
5956  1.386311  8.383548  5.581180  ...  0.898035  0.110692  0.315140
1750  5.525483  4.579800  8.411751  ...  0.903933  0.556578  0.711853
39    1.493487  4.453221  1.712647  ...  0.578597  0.978671  0.119204
4475  0.966090  5.927552  8.076927  ...  0.810061  0.675690  0.472726
7048  5.482199  4.890674  8.735396  ...  0.285609  0.959997  0.212946
...        ...       ...       ...  ...       ...       ...       ...
1098  7.057640  3.426831  1.123781  ...  0.466431  0.213842  0.742699
4471  4.127610  9.009955  1.101530  ...  0.196859  0.717299  0.509883
4490  1.898815  7.778207  1.140012  ...  0.885061  0.638442  0.589550
4966  7.620765  9.513923  7.409730  ...  0.872990  0.589249  0.299006
3585  6.465625  4.864033  4.874330  ...  0.461006  0.742747  0.511005

[1464 rows x 12 columns]


In [ ]:
print(y_train)

[1 1 0 ... 1 1 1]


In [ ]:
print(y_test)

[1 1 0 ... 1 1 1]


##Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train)

[[ 0.03510113  0.26053462 -1.4179578  ...  0.35400438 -1.01048018
   0.73562324]
 [-1.28459774  1.55172093  0.3389957  ... -0.8508701   0.06964137
   1.22537943]
 [ 1.12367455 -1.42835381 -0.40620163 ... -0.51157908 -0.56427187
   0.13618288]
 ...
 [-1.3298243   0.39678492 -0.23968954 ...  1.32865283 -1.32647884
   1.23007386]
 [ 1.24747697  1.62317905 -0.96151884 ...  1.02469687  1.35605976
  -1.50363513]
 [-0.74906657 -0.20778294  0.79512009 ...  0.98539771  1.39975271
   1.763844  ]]


In [ ]:
print(X_test)

[[-1.31375311  1.19072548  0.18163901 ...  1.43454454 -1.45090842
  -0.72749018]
 [ 0.17049696 -0.17484854  1.19725626 ...  1.45611543  0.18102415
   0.71783486]
 [-1.27532118 -0.22029122 -1.20640232 ...  0.26612758  1.72587728
  -1.44133767]
 ...
 [-1.12997616  0.97340354 -1.41186527 ...  1.38708755  0.48064537
   0.27225363]
 [ 0.92183632  1.59653863  0.83772821 ...  1.34293716  0.30060024
  -0.7862719 ]
 [ 0.50761897 -0.07280676 -0.07198088 ... -0.16398892  0.86240033
  -0.01390625]]


##Training the Random Forest Classification model on the Training set

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 1)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=1, verbose=0,
                       warm_start=False)

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[659  49]
 [129 627]]


0.8784153005464481

##Cross-validation and accuracy

In [ ]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(classifier, X_train,y_train, cv= 10 , scoring= 'f1_macro' )
scores

array([0.89049799, 0.90264844, 0.86818265, 0.89583619, 0.85295285,
       0.84919521, 0.86122053, 0.8473476 , 0.8716133 , 0.86638204])

In [ ]:
scores.mean()

0.8705876805631192

##Stratified K-Fold Cross Validation

In [ ]:
from sklearn.metrics import f1_score 
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits= 5 , shuffle= True , random_state= 1 )
f1_scores = []
#run for every split
for train_index, test_index in skf.split(X_train, y_train):
 x_train, x_test = X_train[train_index],X_train[test_index]
 Y_train, Y_test = y_train[train_index], y_train[test_index]
 model = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 1).fit(x_train, Y_train)
 #save result to list
 f1_scores.append(f1_score(y_true=Y_test, y_pred=model.predict(x_test), pos_label= 1 )) 


In [ ]:
f1_scores

[0.8740088105726872,
 0.871934604904632,
 0.8797862867319681,
 0.8681614349775785,
 0.8856885688568857]

In [ ]:
from sklearn.metrics import (recall_score, accuracy_score, precision_score, f1_score,
confusion_matrix)
new_predictions = classifier.predict(X_test)
cnf_mat = confusion_matrix(y_true=y_test, y_pred=new_predictions, labels=[0,1])
cnf_mat

array([[659,  49],
       [129, 627]])

In [ ]:
accuracy = accuracy_score(y_true=y_test, y_pred=new_predictions)
print( 'Accuracy: {}%' .format(round(accuracy* 100 ), 2 )) 

Accuracy: 88%


In [ ]:
precision = precision_score(y_true=y_test, y_pred=new_predictions, pos_label= 0 )
print( 'Precision: {}' .format(round(precision* 100 ), 2 ))

Precision: 84


In [ ]:
recall = recall_score(y_true=y_test, y_pred=new_predictions, pos_label= 0 )
print( 'Recall: {}' .format(round(recall* 100 ), 2 ))

Recall: 93


In [ ]:
f1 = f1_score(y_true=y_test, y_pred=new_predictions, pos_label= 0 )
print( 'F1: {}' .format(round(f1* 100 ), 2 ))

F1: 88


In [ ]:
# Building the model
from sklearn.ensemble import ExtraTreesClassifier
extc = ExtraTreesClassifier(random_state = 1)
  
# Training the model
extc.fit(X_train, y_train)

ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='auto',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_impurity_split=None,
                     min_samples_leaf=1, min_samples_split=2,
                     min_weight_fraction_leaf=0.0, n_estimators=100,
                     n_jobs=None, oob_score=False, random_state=1, verbose=0,
                     warm_start=False)

In [ ]:
y_pred2 = extc.predict(X_test)

In [ ]:
cm2 = confusion_matrix(y_test, y_pred)
print(cm2)
accuracy_score(y_test, y_pred2)

[[659  49]
 [129 627]]


0.924863387978142

In [ ]:
f2 = f1_score(y_test, y_pred, pos_label= 0 )
print( 'F2: {}' .format(round(f1* 100 ), 2 ))

F2: 88


In [ ]:
recall = recall_score(y_test, y_pred, pos_label= 0 )
print( 'Recall: {}' .format(round(recall* 100 ), 2 ))

Recall: 93


In [ ]:
param_dict = {'n_estimators':[50, 100, 300, 500, 1000],'min_samples_split':[2, 3, 5, 7, 9],'min_samples_leaf':[1, 2, 4, 6, 8],'max_features':['auto', 'sqrt', 'log2', None]}

In [ ]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(extc,param_grid = param_dict,cv = 3,verbose = 1,n_jobs = -1)
grid.fit(X_train,y_train)

Fitting 3 folds for each of 500 candidates, totalling 1500 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  46 tasks      | elapsed:   57.4s
[Parallel(n_jobs=-1)]: Done 196 tasks      | elapsed:  3.7min
[Parallel(n_jobs=-1)]: Done 446 tasks      | elapsed:  8.0min
[Parallel(n_jobs=-1)]: Done 796 tasks      | elapsed: 14.3min
[Parallel(n_jobs=-1)]: Done 1246 tasks      | elapsed: 23.9min
[Parallel(n_jobs=-1)]: Done 1500 out of 1500 | elapsed: 31.5min finished


GridSearchCV(cv=3, error_score=nan,
             estimator=ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0,
                                            class_weight=None, criterion='gini',
                                            max_depth=None, max_features='auto',
                                            max_leaf_nodes=None,
                                            max_samples=None,
                                            min_impurity_decrease=0.0,
                                            min_impurity_split=None,
                                            min_samples_leaf=1,
                                            min_samples_split=2,
                                            min_weight_fraction_leaf=0.0,
                                            n_estimators=100, n_jobs=None,
                                            oob_score=False, random_state=1,
                                            verbose=0, warm_start=False),
             iid='deprecated',

In [ ]:
grid.best_params_

{'max_features': 'auto',
 'min_samples_leaf': 2,
 'min_samples_split': 2,
 'n_estimators': 1000}

In [ ]:
grid.best_score_

0.9275956284153005